kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongodb
  namespace: roboshop 
  labels:
    app: mongodb
    project: roboshop
    tier: db

spec:
  replicas: 1
  selector:
    matchLabels:
     app: mongodb
     project: roboshop
     tier: db
    
  template:
    metadata:
     name: mongodb
     labels:
      app: mongodb
      project: roboshop
      tier: db

    spec:
      contaiers:
      - name: mongodb
        image: {{ .Values.deployment.imageURL }}:{{ .Values.deployment.imageVersion }}
        imagePullPolicy: Always
      
